development:
  adapter: postgresql
  database: musicscraper_development
  username: postgres
  password: '32@husker98vespa'
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: musicscraper_test
  username: postgres
  password: 'yourpassword'
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: musicscraper_production
  username: postgres
  password: 'yourpassword'
  host: localhost
  port: 5432



# postgres:
#   adapter: postgresql
#   database: will_paginate
#   min_messages: warning
#   username: postgres
#   password: '32@husker98vespa'
#   host: localhost
#   port: 5432

